version: "3.2"
services:
  auth:
    container_name: authorisation
    command: node src/server.js
    build:
      context: ./services/auth/ 
      dockerfile: Dockerfile
    ports:
      - published: ${AUTH_APP_PORT:-3000}
        target: 3000
    volumes:
      - ./services/auth/:/app
    environment:
      JWT_SECRET: ${JWT_SECRET}

  database:
    container_name: postgres
    restart: always
    build:
      context: ./services/database
      dockerfile: Dockerfile
    ports: 
    - ${POSTGRES_PORT}:5432
    volumes:
    - ./services/database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

