name: Pull Request Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Netguru job
jobs:
  # Build job
  Test:
    # The type of runner that the job will run on
    name: Test API
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2         
                      
      # Start staging database
      - name: Start staging database
        run: docker-compose -f docker-compose-test.yml up -d stage_database
        
      # Test api
      - name: Test API
        run: docker-compose -f docker-compose-test.yml up --exit-code-from api --build api
